# Generated by Django 6.1.1 on 2026-10-05 06:27

import api.images
import api.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('role', models.CharField(choices=[('user', 'Người dùng'), ('expert', 'Chuyên gia')], db_index=True, default='user', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted_at', models.DateTimeField()),
                ('terms_version', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'người dùng',
                'verbose_name_plural': 'người dùng',
                'db_table': 'users',
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_image', models.ImageField(max_length=500, upload_to=api.images.diagnosis_original_path)),
                ('processed_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=api.images.diagnosis_processed_path)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('done', 'Hoàn tất'), ('failed', 'Lỗi')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('healthy', 'Khỏe mạnh'), ('mild', 'Nhẹ'), ('moderate', 'Trung bình'), ('severe', 'Nặng')], db_index=True, max_length=20, null=True)),
                ('leaf_area_px', models.PositiveIntegerField(blank=True, null=True)),
                ('lesion_area_px', models.PositiveIntegerField(blank=True, null=True)),
                ('infected_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('lesion_count', models.PositiveIntegerField(blank=True, null=True)),
                ('lesions', models.JSONField(blank=True, null=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lịch sử chẩn đoán',
                'verbose_name_plural': 'lịch sử chẩn đoán',
                'db_table': 'diagnosis_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='error_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'báo lỗi',
                'verbose_name_plural': 'báo lỗi',
                'db_table': 'error_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('accepted', 'Chấp nhận'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=20)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.diagnosishistory')),
            ],
            options={
                'verbose_name': 'phản hồi',
                'verbose_name_plural': 'phản hồi',
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', False), ('email__isnull', False), _connector='OR'), name='users_active_requires_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='users_username_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='diagnosishistory',
            index=models.Index(fields=['user', 'created_at'], name='idx_dh_user_created'),
        ),
        migrations.AddIndex(
            model_name='diagnosishistory',
            index=models.Index(fields=['user', 'is_bookmarked'], name='idx_dh_user_bookmarked'),
        ),
        migrations.AddConstraint(
            model_name='diagnosishistory',
            constraint=models.CheckConstraint(condition=models.Q(('infected_ratio__isnull', True), models.Q(('infected_ratio__gte', 0), ('infected_ratio__lte', 1)), _connector='OR'), name='dh_ratio_between_0_1'),
        ),
        migrations.AddConstraint(
            model_name='diagnosishistory',
            constraint=models.CheckConstraint(condition=models.Q(('lesion_area_px__isnull', True), ('leaf_area_px__isnull', True), ('lesion_area_px__lte', models.F('leaf_area_px')), _connector='OR'), name='dh_lesion_within_leaf'),
        ),
        migrations.AddConstraint(
            model_name='diagnosishistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'done'), _negated=True), models.Q(('infected_ratio__isnull', False), ('leaf_area_px__isnull', False), ('lesion_area_px__isnull', False), ('lesion_count__isnull', False), ('severity__isnull', False)), _connector='OR'), name='dh_done_requires_result'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(condition=models.Q(('is_resolved', False)), fields=['created_at'], name='idx_er_unresolved'),
        ),
    ]
